spring:
  application:
    name: ehCache
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: root 
  cache:  
    jcache:
      config: 
        classpath:ehcache.xml
  jpa:
    show-sql: true 